# Generated by Django 4.1.8 on 2023-10-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("drawing_number", models.CharField(max_length=255, unique=True)),
                ("name_in_russian", models.CharField(max_length=255)),
                ("name_in_chinese", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="itembase.item",
                    ),
                ),
            ],
        ),
    ]
