# Generated by Django 4.1.8 on 2023-10-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("itembase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="drawing_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="itembase.item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="scheme_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("scheme_name", "drawing_number")},
        ),
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
        migrations.RemoveField(
            model_name="item",
            name="name_in_chinese",
        ),
        migrations.RemoveField(
            model_name="item",
            name="name_in_russian",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
