# Generated by Django 4.1.8 on 2023-10-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("itembase", "0002_alter_item_drawing_number_alter_item_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="itembase.item",
            ),
        ),
    ]
