# Generated by Django 4.1.8 on 2023-10-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("itembase", "0003_alter_item_parent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="item",
            name="code",
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="itembase.item",
            ),
        ),
        migrations.RemoveField(
            model_name="item",
            name="drawing_number",
        ),
        migrations.RemoveField(
            model_name="item",
            name="scheme_name",
        ),
    ]
