# Generated by Django 4.1.8 on 2023-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itembase", "0004_alter_item_unique_together_item_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="name_chinese",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="name_russian",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="scheme_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
