# Generated by Django 4.1.8 on 2023-10-27 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itembase", "0005_item_name_chinese_item_name_russian_item_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
